In [23]:
import pandas as pd
import geopandas as gpd
import folium

In [24]:
df = pd.read_csv('Desktop/Artificial Intelligence/Connecticut Weather_Stations.csv', encoding='unicode_escape')

In [25]:
df.head()

                           Station  Longitude   Latitude
0  Bridgeport Sikorsky Mem Airport    -73.1270    41.1640
1                 Bulls Bridge Dam    -73.4830    41.6500
2                       Burlington    -72.9700    41.7700
3                   Cockaponset Rs    -72.5197    41.4614
4                         Coventry    -72.3100    41.7700

In [26]:
gdf = gpd.GeoDataFrame(
    df, 
    geometry=gpd.points_from_xy(df['Longitude '], df['Latitude ']),
    crs="EPSG:4326"  # Standard WGS84 coordinate reference system
)
gdf.head()

,Station,Longitude,Latitude,geometry
0,Bridgeport Sikorsky Mem Airport,-73.1270,41.1640,POINT (-73.127 41.164)
1,Bulls Bridge Dam,-73.4830,41.6500,POINT (-73.483 41.65)
2,Burlington,-72.9700,41.7700,POINT (-72.97 41.77)
3,Cockaponset Rs,-72.5197,41.4614,POINT (-72.5197 41.4614)
4,Coventry,-72.3100,41.7700,POINT (-72.31 41.77)

In [27]:
# Reads the data
CT = gpd.read_file('Desktop/Artificial Intelligence/Connecticut_Routes_-8583715507025981790/deepgis_DEEP_ROUTES.shp')
CT.crs

<Projected CRS: EPSG:2234>
Name: NAD83 / Connecticut (ftUS)
Axis Info [cartesian]:
- X[east]: Easting (US survey foot)
- Y[north]: Northing (US survey foot)
Area of Use:
- name: United States (USA) - Connecticut - counties of Fairfield; Hartford; Litchfield; Middlesex; New Haven; New London; Tolland; Windham.
- bounds: (-73.73, 40.98, -71.78, 42.05)
Coordinate Operation:
- name: SPCS83 Connecticut zone (US survey foot)
- method: Lambert Conic Conformal (2SP)
Datum: North American Datum 1983
- Ellipsoid: GRS 1980
- Prime Meridian: Greenwich

In [28]:
gdf.crs

<Geographic 2D CRS: EPSG:4326>
Name: WGS 84
Axis Info [ellipsoidal]:
- Lat[north]: Geodetic latitude (degree)
- Lon[east]: Geodetic longitude (degree)
Area of Use:
- name: World.
- bounds: (-180.0, -90.0, 180.0, 90.0)
Datum: World Geodetic System 1984 ensemble
- Ellipsoid: WGS 84
- Prime Meridian: Greenwich

In [29]:
gdf_projected = gdf.to_crs(CT.crs)

In [30]:
gdf_projected.crs

<Projected CRS: EPSG:2234>
Name: NAD83 / Connecticut (ftUS)
Axis Info [cartesian]:
- X[east]: Easting (US survey foot)
- Y[north]: Northing (US survey foot)
Area of Use:
- name: United States (USA) - Connecticut - counties of Fairfield; Hartford; Litchfield; Middlesex; New Haven; New London; Tolland; Windham.
- bounds: (-73.73, 40.98, -71.78, 42.05)
Coordinate Operation:
- name: SPCS83 Connecticut zone (US survey foot)
- method: Lambert Conic Conformal (2SP)
Datum: North American Datum 1983
- Ellipsoid: GRS 1980
- Prime Meridian: Greenwich

In [31]:
gdf_projected.columns

Index(['Station', 'Longitude ', 'Latitude ', 'geometry'], dtype='object')

In [32]:
# Lengths of variables a, b and c are the same
a = ['Bridgeport Sikorsky Mem Airport', 'Bulls Bridge Dam', 'Burlington', 'Cockaponset Rs', 'Coventry', 'Danbury', 'Falls Village', 'Groton',
     'Hartford Brainard Fd', 'Hartford Bradley International Airport', 'Mansfield Hollow Lake', 'Middletown 4 W', 'Mount Carmel', 'New Haven',
     'Norfolk 2 Sw', 'Norwich Pub Util Plt', 'Shepaug Dam', 'Stamford 5 N', 'Storrs', 'West Thompson Lake', 'Wigwam Reservoir']
b = gdf_projected['Longitude ']
c = gdf_projected['Latitude ']
                
m = folium.Map(location=[c[11], b[11]],
                 zoom_start=9)

# This 'for' loop creates an interactive map with a marker at each of the 21 weather
# stations in Connecticut
for i in range(len(a)):
     folium.Marker([c[i], b[i]],
                  popup=a[i]).add_to(m)  
m